### ISSUE TITLE
Import calendar era information for CJK from the DILA Time Authority Database

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/cc-calendar-systems#27]
https://github.com/DILA-edu/Authority-Databases/tree/master/authority_time/SQL

Active site: https://authority.dila.edu.tw/time/

**Comment by eroux** [comment]
just as a side note, here are all the 1400 eras (Chinese and others) recorded on Wikidata:

https://query.wikidata.org/#select%20%3Fs%20where%20%7B%20%3Ft%20wdt%3AP279%2a%20wd%3AQ256408%20.%20%3Fs%20wdt%3AP31%20%3Ft%20%7D%0A

**Comment by eroux** [comment]
I can extract the data, what format would be best? (there are sometimes different languages associated with the eras in the DILA database)

**Comment by ronaldtse** [comment]
Would be best to extract them in YAML so we can import back to a document for distribution (because they will need to be vetted).

**Comment by eroux** [comment]
Sure, I'm just not sure what code we should assign these... for instance let's start with DILA era 1: `建武`, this is the only label, but unfortunately it's an ambiguous one as 4 different eras are named that way... should the code be "dila-1", or just "chinese-era-1"? What about something like:

```yaml
- code: dila1
  name: 建武
  reign_of: 光武帝
  ref: |
    * Dharma Drum Institute of Liberal Arts Time Database, era id 1
    * https://www.wikidata.org/wiki/Q8012586 
```

? (note that the wikidata Q id needs to be reconciled manually or semi-automatically, but I can't do it for all the DILA eras)
